# Base de datos de planetas

## Dataset Glossary

**Planet** - Name of the Planet.

**Color** - Color of the Planet.

**Mass (10^24kg)** - This is the mass of the planet in septillion (1 followed by 24 zeros) kilograms or sextillion (1 followed by 21 zeros) tons. Strictly speaking, tons are measures of weight, not mass, but are used here to represent the mass of one ton of material under Earth gravity.

**Diameter (km)** - The diameter of the planet at the equator, the distance through the center of the planet from one point on the equator to the opposite side, in kilometers or miles.

**Density (kg/m^3)** - The average density (mass divided by volume) of the whole planet (not including the atmosphere for the terrestrial planets) in kilograms per cubic meter or pounds per cubic foot. Strictly speaking, pounds are measures of weight, not mass, but are used here to represent the mass of one pound of material under Earth's gravity.

**Gravity (m/s^2)** - The gravitational acceleration on the surface at the equator in meters per second squared or feet per second squared, including the effects of rotation. For the gas giant planets, the gravity is given at the 1 bar pressure level in the atmosphere. The gravity on Earth is designated as 1 "G", so the Earth ratio fact sheets give the gravity of the other planets in G's.

**Escape Velocity (km/s)** - Initial velocity, in kilometers per second or miles per second, needed at the surface (at the 1 bar pressure level for the gas giants) to escape the body's gravitational pull, ignoring atmospheric drag.

**Rotation Period (hours)** - This is the time it takes for the planet to complete one rotation relative to the fixed background stars (not relative to the Sun) in hours. Negative numbers indicate retrograde (backward relative to the Earth) rotation.

**Length of Day (hours)** - The average time in hours for the Sun to move from the noon position in the sky at a point on the equator back to the same position.

**Distance from Sun (10^6 km)** - This is the average distance from the planet to the Sun in millions of kilometers or millions of miles, also known as the semi-major axis. All planets have orbits that are elliptical, not perfectly circular, so there is a point in the orbit at which the planet is closest to the Sun, the perihelion, and a point furthest from the Sun, the aphelion. The average distance from the Sun is midway between these two values. The average distance from the Earth to the Sun is defined as 1 Astronomical Unit (AU), so the ratio table gives this distance in AU.

**Perihelion, Aphelion (10^6 km)** - The closest and furthest points in a planet's orbit about the Sun, see "Distance from Sun" above.

**Orbital Period (days)** - This is the time in Earth days for a planet to orbit the Sun from one vernal equinox to the next. Also known as the tropical orbit period, this is equal to a year on Earth.

**Orbital Velocity (km/s)** - The average velocity or speed of the planet as it orbits the Sun, in kilometers per second or miles per second.

**Orbital Inclination (degrees)** - The angle in degrees at which a planets orbit around the Sun is tilted relative to the ecliptic plane. The ecliptic plane is defined as the plane containing the Earths orbit, so the Earth's inclination is 0.

**Orbital Eccentricity** - This is a measure of how far a planets orbit about the Sun (or the Moons orbit about the Earth) is from being circular. The larger the eccentricity, the more elongated the orbit, an eccentricity of 0 means the orbit is a perfect circle. There are no units for eccentricity.

**Obliquity to Orbit (degrees)** - The angle in degrees the axis of a planet (the imaginary line running through the center of the planet from the north to south poles) is tilted relative to a line perpendicular to the planet's orbit around the Sun, north pole defined by the right-hand rule. Venus rotates in a retrograde direction, opposite the other planets, so the tilt is almost 180 degrees, it is considered to be spinning with its "top", or north pole pointing "downward" (southward). Uranus rotates almost on its side relative to the orbit, Pluto is pointing slightly "down". The ratios with Earth refer to the axis without reference to north or south.

**Mean Temperature (C)** - This is the average temperature over the whole planets surface (or for the gas giants at the one bar level) in degrees C (Celsius or Centigrade) or degrees F (Fahrenheit). For Mercury and the Moon, for example, this is an average over the sunlit (very hot) and dark (very cold) hemispheres and so is not representative of any given region on the planet, and most of the surface is quite different from this average value. As with the Earth, there will tend to be variations in temperature from the equator to the poles, from the day to night sides, and seasonal changes on most planets.

**Number of Moons** - This gives the number of IAU officially confirmed moons orbiting the planet. New moons are still being discovered.

**Ring System?** - This tells whether a planet has a set of rings around it, Saturn being the most obvious example.

**Global Magnetic Field?** - This tells whether the planet has a measurable large-scale magnetic field. Mars and the Moon have localized regional magnetic fields but no global field.

**Surface Temperature (C)** - Surface temperature of the planet in degrees Celsius.

**Atmospheric Composition** - Composition of the planet's atmosphere.

**Atmospheric Pressure (bars)** - This is the atmospheric pressure (the weight of the atmosphere per unit area) at the surface of the planet in bars or atmospheres. The surfaces of Jupiter, Saturn, Uranus, and Neptune are deep in the atmosphere and the location and pressures are not known.
**Surface Features** - Notable features on the planet's surface.

**Composition** - Composition of the planet's materials.

In [4]:
# Cargar todas las librer√≠as
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import re

In [5]:
# Mostrar base de datos
planets_df = pd.read_csv('planets_updated.csv')
display(planets_df)

,Planet,Color,Mass (10^24kg),Diameter (km),Density (kg/m^3),Surface Gravity(m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),...,Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?,Surface Temperature (C),Atmospheric Composition,Atmospheric Pressure (bars),Surface Features,Composition
0,Mercury,Grey,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,...,167,0,0,No,Yes,-173 to 427,Mostly None,Trace,"Craters, Scarps",Rock and Metal
1,Venus,Brown and Grey,4.870,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,...,464,92,0,No,No,462,Carbon Dioxide (96.5%),92,"Volcanoes, Venusian Plains",Rock and Metal
2,Earth,"Blue, Brown Green and White",5.970,12756,5514,9.8,11.2,23.9,24.0,149.6,...,15,1,1,No,Yes,-89 to 58,"Nitrogen (78.1%), Oxygen",1,"Mountains, Oceans, Forests","Rock, Water, and Air"
3,Mars,"Red, Brown and Tan",0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,...,-65,0.01,2,No,No,-153 to 20,Carbon Dioxide (95.3%),0.006,"Valles Marineris, Olympus Mons",Rock and Ice
4,Jupiter,"Brown, Orange and Tan, with White cloud stripes",1898.000,142984,1326,23.1,59.5,9.9,9.9,778.5,...,-110,Unknown,79,Yes,Yes,-108 to -150,"Hydrogen, Helium",Unknown,"Great Red Spot, Jupiter's Rings",Gas and Liquid
5,Saturn,"Golden, Brown, and Blue-Grey",568.000,120536,687,9.0,35.5,10.7,10.7,1432.0,...,-140,Unknown,82,Yes,Yes,-178 to -228,"Hydrogen, Helium",Unknown,"Rings, Cassini Division, Saturn's Hexagon",Gas and Liquid
6,Uranus,Blue-Green,86.800,51118,1270,8.7,21.3,-17.2,17.2,2867.0,...,-195,Unknown,27,Yes,Yes,-197,"Hydrogen, Helium",Unknown,"Rings, Miranda's Cliff, Oberon's Craters",Gas and Ice
7,Neptune,Blue,102.000,49528,1638,11.0,23.5,16.1,16.1,4515.0,...,-200,Unknown,14,Yes,Yes,-201,"Hydrogen, Helium",Unknown,"Great Dark Spot, Triton's Geysers",Gas and Ice

In [18]:
planets_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   planet                   8 non-null      object
 1   color                    8 non-null      object
 2   mass                     8 non-null      float64
 3   diameter                 8 non-null      int64
 4   density                  8 non-null      int64
 5   surface_gravity          8 non-null      float64
 6   escape_velocity          8 non-null      float64
 7   rotation_period          8 non-null      float64
 8   length_of_day            8 non-null      float64
 9   distance_from_sun        8 non-null      float64
 10  perihelion               8 non-null      float64
 11  aphelion                 8 non-null      float64
 12  orbital_period           8 non-null      object
 13  orbital_velocity         8 non-null      float64
 14  orbital_inclination      8 non-null      float64
 15  orbital_eccentricity     8 non-null      float64
 16  obliquity_to_orbit       8 non-null      float64
 17  mean_temperature         8 non-null      int64
 18  surface_pressure         8 non-null      object
 19  number_of_moons          8 non-null      int64
 20  ring_system              8 non-null      object
 21  global_magnetic_field    8 non-null      object
 22  surface_temperature      8 non-null      object
 23  atmospheric_composition  8 non-null      object
 24  atmospheric_pressure     8 non-null      object
 25  surface_features         8 non-null      object
 26  composition              8 non-null      object
dtypes: float64(12), int64(4), object(11)
memory usage: 1.8+ KB

In [19]:
planets_df.describe()

,mass,diameter,density,surface_gravity,escape_velocity,rotation_period,length_of_day,distance_from_sun,perihelion,aphelion,orbital_velocity,orbital_inclination,orbital_eccentricity,obliquity_to_orbit,mean_temperature,number_of_moons
count,8.000000,8.000000,8.000000,8.000000,8.00000,8.000000,8.00000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000
mean,333.326500,50087.125000,3130.125000,9.737500,21.33750,-544.612500,890.90000,1267.025000,1226.162500,1307.912500,21.412500,2.325000,0.060250,47.741750,-8.000000,25.625000
std,660.538057,53916.366175,2104.022368,6.040089,18.67473,2191.819718,1661.92169,1626.047146,1599.115396,1653.781713,15.183397,2.150581,0.065447,60.364836,225.783714,35.136215
min,0.330000,4879.000000,687.000000,3.700000,4.30000,-5832.500000,9.90000,57.900000,46.000000,69.800000,5.400000,0.000000,0.007000,0.034000,-200.000000,0.000000
25%,3.813000,10776.000000,1312.000000,7.450000,9.05000,3.125000,14.75000,139.250000,137.200000,141.300000,8.975000,1.175000,0.015250,18.325000,-153.750000,0.750000
50%,46.385000,31142.000000,2786.000000,8.950000,16.25000,13.400000,20.60000,503.250000,473.650000,532.850000,18.600000,1.800000,0.048000,25.950000,-87.500000,8.000000
75%,218.500000,68472.500000,5289.500000,10.100000,26.50000,24.075000,719.02500,1790.750000,1701.375000,1880.225000,31.100000,2.725000,0.062500,45.675000,53.000000,40.000000
max,1898.000000,142984.000000,5514.000000,23.100000,59.50000,1407.600000,4222.60000,4515.000000,4471.100000,4558.900000,47.400000,7.000000,0.206000,177.400000,464.000000,82.000000

In [6]:
# Nombres de columnas originales
original_columns = planets_df.columns
print(original_columns)

Index(['Planet', 'Color', 'Mass (10^24kg)', 'Diameter (km)',
       'Density (kg/m^3)', 'Surface Gravity(m/s^2)', 'Escape Velocity (km/s)',
       'Rotation Period (hours)', 'Length of Day (hours)',
       'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)',
       'Aphelion (10^6 km)', 'Orbital Period (days)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (degrees)',
       'Orbital Eccentricity', 'Obliquity to Orbit (degrees)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?', 'Surface Temperature (C)',
       'Atmospheric Composition', 'Atmospheric Pressure (bars)',
       'Surface Features', 'Composition'],
      dtype='object')

In [7]:
# Funci√≥n para convertir a snake_case
def to_snake_case(column_name):
    s = column_name.lower()  # Convertir a min√∫sculas
    s = re.sub(r'[^a-z0-9]+', '_', s)  # Reemplazar caracteres no alfanum√©ricos con guiones bajos
    s = s.strip('_')  # Eliminar guiones bajos extra al principio o al final
    return s

In [8]:
# Funci√≥n para quitar las unidades (y cualquier informaci√≥n entre par√©ntesis)
def remove_units(column_name):
    return re.sub(r'\(.*\)', '', column_name).strip()

# Quitar las unidades de los nombres de las columnas
columns_without_units = [remove_units(col) for col in original_columns]

# Convertir cada nombre de columna (sin unidades) a snake_case
snake_case_columns_without_units = [to_snake_case(col) for col in columns_without_units]
snake_case_columns_without_units

['planet',
 'color',
 'mass',
 'diameter',
 'density',
 'surface_gravity',
 'escape_velocity',
 'rotation_period',
 'length_of_day',
 'distance_from_sun',
 'perihelion',
 'aphelion',
 'orbital_period',
 'orbital_velocity',
 'orbital_inclination',
 'orbital_eccentricity',
 'obliquity_to_orbit',
 'mean_temperature',
 'surface_pressure',
 'number_of_moons',
 'ring_system',
 'global_magnetic_field',
 'surface_temperature',
 'atmospheric_composition',
 'atmospheric_pressure',
 'surface_features',
 'composition']

In [9]:
#remplazo las columnas en el dataframe
planets_df.columns = snake_case_columns_without_units

In [21]:
# renombra las columnas
planets_df = planets_df.rename(columns = {
        'surface_gravity':'gravity',
        'surface_pressure':'pressure',
        'surface_temperature':'temperature',
        'Day': 'day',
        }
)

In [24]:
#Elimino la coliumna pressure porque es ambiagua con respecto a 'atmospheric_pressure'
planets_df.drop('pressure', axis=1, inplace=True)

In [22]:
#compruebo
display(planets_df[planets_df['planet'] == 'Venus'])
print()

,planet,color,mass,diameter,density,gravity,escape_velocity,rotation_period,length_of_day,distance_from_sun,...,mean_temperature,pressure,number_of_moons,ring_system,global_magnetic_field,temperature,atmospheric_composition,atmospheric_pressure,surface_features,composition
1,Venus,Brown and Grey,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,...,464,92,0,No,No,462,Carbon Dioxide (96.5%),92,"Volcanoes, Venusian Plains",Rock and Metal

In [ ]:
#Muestra el dataframe ordenado por gravedad
display(planets_df.sort_values(by='surface_gravity', ascending=False))

In [23]:
# Factor de conversi√≥n de bars a atm
floantconversion_factor = 0.986923

# Convertir la columna de presi√≥n de bars a atm
planets_df['pressure'] = planets_df['pressure'] * conversion_factor

# Si deseas eliminar la columna original en bars, puedes usar:
# planets_df.drop('Surface Pressure (bars)', axis=1, inplace=True)

TypeError: can't multiply sequence by non-int of type 'float'